#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -z "$CI" ]
then
    echo "Husky: Running pre-commit hooks.";
    echo "";
    echo "Run git with --no-verify to skip hooks"
    npm run doc;
    git add ./docs;
    npm run build;
    npm run test;
fi
